import {OpenAPIHono, z} from '@hono/zod-openapi';
//we can import the inputs and outputs from the external files , we did that in ordfer for the open api schema to be made

import { createRoute } from '@hono/zod-openapi';
import { paramsSchema } from './inputs';
import { userSchema } from './outputs';
import { swaggerUI } from '@hono/swagger-ui';
import { DefaultService } from '../generated';

//so basically we are writting our routes like this and we are descriping the inputs and outputs like that , so that the openapi schema can be generated 
//adding the swaager ui library to make the api info page 
//usually we use a language like rust to make backends where the making of the openapi schema files are fairly easy
//so that we dont have to write this complicated way of writting routes 

//NOW FOR AUTOGENERATED CLIENTS >>

//if we run this command npx openapi-typescript-codegen --input ./openapispec.json --output ./generated
//then it will scrape the spec file and create a client for us in generated folder where users can just call a function and interact with the backend 

//usually we dont ever do this in the server here as we are making the server talking too itself
//usually we do is copy the openapi spec file generated from this api and create another node.js process and paste it there
//and then run the command npx openapi-typescript-codegen --input ./spec.json --output ./generated
//and generate a clinet and then we do a new DefaultService call and interact with this api

//a basic usage i can think of is  , rememember paula told about the credit info of users in australia ?
//there we can ask the beraue for their api config that is the openapi schema , then after copying it then we can create a node.js process 
//and from that node.js process we can get the user's credit information and show them to the frontend 

//NOW SEE THE (TRADER APP OPENAPISPEC HONO EXAMPLE) FOLDER TO SEE THIS IMPLEMENTATION
/*
const service = new DefaultService();
const Getresponse = await DefaultService.getUser("1"); //calling the getUser functions to get the user with id 1
const Postresponse = await DefaultService.postUser("1") ; //calling the postuser function to to interact witht the post route of the api
*/

const app = new OpenAPIHono();

const getUserRoute = createRoute({
  method : 'get',
  path : '/user/{id}',
  request : {
    params : paramsSchema
  },
  responses : {
    200 : {
      content : {
        'application/json' : {
          schema : userSchema
        }
      },
      description : "Get the users details"
    }
  }
});

const PostUserRoute = createRoute({
  method : 'post',
  path : '/user/{id}',
  request : {
    params : paramsSchema
  },
  responses : {
    200 : {
      content : {
        'application/json' : {
          schema : userSchema
        }
      },
      description : "Get the users details"
    }
  }
});

app.openapi(getUserRoute , (c) => {
  const {id} = c.req.valid("param");
  return c.json({
    id,
    age : 20,
    name : 'Ultra - man'
  })
});

app.openapi(PostUserRoute , (c) => {
  const {id} = c.req.valid("param");
  return c.json({
    id,
    age : 20,
    name : 'Ultra - man'
  })
});

app.doc('/doc' , {
  openapi : '3.0.0',
  info : {
    version : '1.0.0',
    title : 'MY API'
  }
});

app.get('/ui' , swaggerUI({url : '/doc'}));

//so when we visit the /doc route we see our open api schema there

export default app;
